name: App variables

outputs:
  artifactId:
    value: ${{ steps.variables.outputs.artifactId }}
  groupId:
    value: ${{ steps.variables.outputs.groupId }}
  appVersion:
    value: ${{ steps.variables.outputs.appVersion }}

runs:
  using: "composite"
  steps:
    - name: Recupera Variaveis
      id: variables
      run: |
        mvn=$(which mvn)
        appVersion=$($mvn -f pom.xml help:evaluate -Dexpression=project.version -q -DforceStdout)
        artifactId=$($mvn -f pom.xml help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
        groupId=$($mvn -f pom.xml help:evaluate -Dexpression=project.groupId -q -DforceStdout)
        echo "appVersion=$appVersion" >> $GITHUB_OUTPUT
        echo "artifactId=$artifactId" >> $GITHUB_OUTPUT
        echo "groupId=$groupId" >> $GITHUB_OUTPUT
      shell: bash
